#ifndef LARAVELGATE_CONFIG_H
#define LARAVELGATE_CONFIG_H

#include <QtCore/qglobal.h>

#define LARAVELGATE_VERSION_MAJOR 1
#define LARAVELGATE_VERSION_MINOR 0
#define LARAVELGATE_VERSION_PATCH 0
#define LARAVELGATE_VERSION_STR   "1.0.0"
#define LARAVELGATE_VERSION       LARAVELGATE_VERSION_CHECK(LARAVELGATE_VERSION_MAJOR, LARAVELGATE_VERSION_MINOR, LARAVELGATE_VERSION_PATCH)
#define LARAVELGATE_VERSION_CHECK QT_VERSION_CHECK

#endif // LARAVELGATE_CONFIG_H
